-- MySQL Script generated by MySQL Workbench
-- lun 14 may 2018 14:36:42 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sustantivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sustantivos` (
  `idsustantivos` INT NOT NULL,
  `esquema_sust` VARCHAR(45) NOT NULL,
  `nombre_sust` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsustantivos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`esquemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`esquemas` (
  `idesquemas` INT NOT NULL,
  `nombre_esquema` VARCHAR(45) NOT NULL,
  `sustantivos_idsustantivos` INT NOT NULL,
  PRIMARY KEY (`idesquemas`),
  INDEX `fk_esquemas_sustantivos_idx` (`sustantivos_idsustantivos` ASC),
  CONSTRAINT `fk_esquemas_sustantivos`
    FOREIGN KEY (`sustantivos_idsustantivos`)
    REFERENCES `mydb`.`sustantivos` (`idsustantivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`triadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`triadas` (
  `idtriadas` INT NOT NULL,
  `conector_triada` VARCHAR(45) NOT NULL,
  `sustantivos_idsustantivos` INT NOT NULL,
  `sustantivos_idsustantivos1` INT NOT NULL,
  `dependencia_triadas` INT NULL,
  PRIMARY KEY (`idtriadas`),
  INDEX `fk_triadas_sustantivos1_idx` (`sustantivos_idsustantivos` ASC),
  INDEX `fk_triadas_sustantivos2_idx` (`sustantivos_idsustantivos1` ASC),
  INDEX `fk_triadas_triadas1_idx` (`dependencia_triadas` ASC),
  CONSTRAINT `fk_triadas_sustantivos1`
    FOREIGN KEY (`sustantivos_idsustantivos`)
    REFERENCES `mydb`.`sustantivos` (`idsustantivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triadas_sustantivos2`
    FOREIGN KEY (`sustantivos_idsustantivos1`)
    REFERENCES `mydb`.`sustantivos` (`idsustantivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triadas_triadas1`
    FOREIGN KEY (`dependencia_triadas`)
    REFERENCES `mydb`.`triadas` (`idtriadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
